#!/usr/bin/env python3
"""Generate a collection-assignment JS for EVERY source note (not just orphans).

Covers both groups so every Zotero item lands in its category/meta/problem
collection — required before zotero_sync.py (Zotero → Obsidian) can run without
wiping categories off the originally-linked notes.

For each `sources/*.md`:
  - category/meta/problem read from the note frontmatter (source of truth)
  - paths built as 🗺️ cat / ⇶ meta / ⚡ problem (same nesting as orphan.bib)
  - itemKey resolved:
      * note has a `zotero:` link  → citationKey → itemKey (from .library.json uri)
      * otherwise (orphan)         → title → single item inside `orphan` collection

Emits `.assign_collections.js` (overwrites; itemKey-based, idempotent). Also prints
categories that do NOT match an existing 🗺️ collection so typos surface instead of
silently creating stray collections.
"""

import json
import re
import sys
import urllib.request
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
VAULT_ROOT = SCRIPT_DIR.parents[1]
SOURCES_DIR = VAULT_ROOT / "sources"
LIBRARY_FILE = SCRIPT_DIR / ".library.json"
OUT_ASSIGN = str(SCRIPT_DIR / ".assign_collections.js")
API = "http://127.0.0.1:23119/api/users/0"


def api_get(path):
    with urllib.request.urlopen(API + path, timeout=15) as r:
        return json.load(r)


def existing_category_names():
    colls = api_get("/collections?limit=200")
    return {c["data"]["name"] for c in colls}, colls


def orphan_title_to_key(colls):
    ok = [c["data"]["key"] for c in colls if c["data"]["name"] == "orphan"]
    if not ok:
        return {}
    ok, start, t2k = ok[0], 0, {}
    while True:
        batch = api_get(f"/collections/{ok}/items?limit=100&start={start}&format=json")
        if not batch:
            break
        for it in batch:
            d = it["data"]
            if d.get("itemType") in ("attachment", "note"):
                continue
            t = (d.get("title") or "").strip().lower()
            if t:
                t2k.setdefault(t, []).append(it["key"])
        start += 100
        if len(batch) < 100:
            break
    return t2k


def library_title_to_key():
    """title → [itemKey] across the WHOLE live library (fallback for items not in
    the `orphan` collection, e.g. freshly imported via .orphan_missing.bib)."""
    t2k, start = {}, 0
    while True:
        batch = api_get(f"/items?limit=100&start={start}&format=json")
        if not batch:
            break
        for it in batch:
            d = it["data"]
            if d.get("itemType") in ("attachment", "note"):
                continue
            t = (d.get("title") or "").strip().lower()
            if t:
                t2k.setdefault(t, []).append(it["key"])
        start += 100
        if len(batch) < 100:
            break
    return t2k


def citationkey_to_itemkey():
    lib = json.loads(LIBRARY_FILE.read_text(encoding="utf-8"))
    out = {}
    for it in lib["items"]:
        ck = it.get("citationKey")
        uri = it.get("uri", "")
        if ck and uri:
            out[ck] = uri.rsplit("/", 1)[-1]
    return out


def extract(fm):
    cats = re.findall(r'category:\s*\n\s*-\s*"\[\[(.+?)\]\]"', fm)
    if not cats:
        m = re.search(r'^category:\s+"?\[\[(.+?)\]\]"?', fm, re.M)
        if m:
            cats = [m.group(1)]
    metas = re.findall(r'meta:\s*\n\s*-\s*"\[\[(.+?)\]\]"', fm)
    probs = re.findall(r'problem:\s*\n\s*-\s*"\[\[(.+?)\]\]"', fm)
    return cats, metas, probs


def build_paths(cats, metas, probs):
    groups = []
    metas_list = metas or [None]
    probs_list = probs or [None]
    for cat in cats:
        base = f"🗺️ {cat}"
        for meta in metas_list:
            mid = base + (f"/⇶ {meta}" if meta else "")
            for prob in probs_list:
                full = mid + (f"/⚡ {prob}" if prob else "")
                if full not in groups:
                    groups.append(full)
    if not cats:
        for meta in metas:
            groups.append(f"⇶ {meta}")
        for prob in probs:
            groups.append(f"⚡ {prob}")
    return [[s.strip() for s in g.split("/") if s.strip()] for g in groups]


JS_TEMPLATE = r"""// Auto-generated by .assign_all_sources.py — covers ALL source notes, matched by itemKey.
// Zotero → Tools → Developer → Run JavaScript (async ON) → Run.
// Run .cleanup_collections.js FIRST if you want a clean slate.

const ASSIGNMENTS = __ASSIGNMENTS_JSON__;  // {itemKey, paths}
const libraryID = Zotero.Libraries.userLibraryID;
const log = (s) => Zotero.debug("[assign-all] " + s);

const cache = new Map();
const ck = (p, n) => (p == null ? "0" : p) + "|" + n;
for (const c of Zotero.Collections.getByLibrary(libraryID, true)) {
    cache.set(ck(c.parentID || null, c.name), c.id);
}
async function ensureCollection(parentID, name) {
    const k = ck(parentID, name);
    if (cache.has(k)) return cache.get(k);
    const coll = new Zotero.Collection();
    coll.libraryID = libraryID; coll.name = name;
    if (parentID != null) coll.parentID = parentID;
    const id = await coll.saveTx();
    cache.set(k, id);
    return id;
}
async function ensurePath(segs) { let p = null; for (const s of segs) p = await ensureCollection(p, s); return p; }

let placed = 0, already = 0, notFound = 0;
const notFoundList = [];
for (const a of ASSIGNMENTS) {
    const item = await Zotero.Items.getByLibraryAndKeyAsync(libraryID, a.itemKey);
    if (!item || item.deleted) { notFound++; notFoundList.push(a.itemKey); continue; }
    const leafIDs = [];
    for (const segs of a.paths) { if (segs.length) leafIDs.push(await ensurePath(segs)); }
    const current = item.getCollections();
    const toAdd = leafIDs.filter(id => !current.includes(id));
    if (!toAdd.length) { already++; continue; }
    item.setCollections([...current, ...toAdd]);
    await item.saveTx();
    placed++;
}
const summary = "Placed " + placed + " items; " + already + " already correct; " + notFound + " not found.";
log(summary);
if (notFoundList.length) log("Not found keys: " + notFoundList.slice(0, 10).join(", "));
return summary;
"""


def main():
    cat_names, colls = existing_category_names()
    t2k = orphan_title_to_key(colls)
    lib_t2k = library_title_to_key()
    ck2ik = citationkey_to_itemkey()

    payload, unresolved, unknown_cats = [], [], {}
    for f in sorted(SOURCES_DIR.glob("*.md")):
        if f.name == ".gitkeep":
            continue
        c = f.read_text(encoding="utf-8")
        fm = c.split("---", 2)[1] if c.startswith("---") else ""
        cats, metas, probs = extract(fm)
        paths = build_paths(cats, metas, probs)
        if not paths:
            continue

        # flag categories with no matching 🗺️ collection
        for cat in cats:
            if f"🗺️ {cat}" not in cat_names:
                unknown_cats.setdefault(cat, []).append(f.stem)

        m = re.search(r"zotero://select(?:/library)?/items/@([a-zA-Z0-9_\-]+)", c)
        itemkey = None
        if m:
            itemkey = ck2ik.get(m.group(1))
        if not itemkey:
            am = re.search(r'aliases:\s*\n\s*-\s*"(.+?)"', fm)
            title = (am.group(1) if am else f.stem).strip().lower()
            keys = t2k.get(title) or lib_t2k.get(title, [])  # orphan coll first, then whole library
            if len(keys) == 1:
                itemkey = keys[0]
        if not itemkey:
            unresolved.append(f.stem)
            continue
        payload.append({"itemKey": itemkey, "paths": paths})

    Path(OUT_ASSIGN).write_text(
        JS_TEMPLATE.replace(
            "__ASSIGNMENTS_JSON__", json.dumps(payload, ensure_ascii=False, indent=2)
        ),
        encoding="utf-8",
    )
    print(f"✅ Resolved {len(payload)} items → {OUT_ASSIGN}")
    if unresolved:
        print(f"⚠️  {len(unresolved)} notes with category but UNRESOLVED itemKey:")
        for s in unresolved:
            print("     ", s)
    if unknown_cats:
        print(f"⚠️  categories with NO matching 🗺️ collection (likely typos):")
        for cat, notes in unknown_cats.items():
            print(f"      '{cat}' ← {notes}")


if __name__ == "__main__":
    main()
