#!/usr/bin/env python3
"""Generate two JavaScript snippets for Zotero:

- `.cleanup_collections.js` — removes every item from emoji-prefixed collections
  (🗺️/⇶/⚡), giving a clean slate. Run this FIRST if a prior bad run scattered
  items into wrong collections.

- `.assign_collections.js` — builds the nested hierarchy
  Category → Meta-note → Problem  (🗺️ → ⇶ → ⚡)
  and adds each item to the LEAF collection only.
  Looks up items via Better BibTeX KeyManager (citation key) with trash filter,
  falls back to case-insensitive title match.

Workflow:
1. Empty Zotero Trash (Right-click Trash → Empty Trash). This clears stale
   BBT KeyManager records that were causing the wrong-item bug.
2. Run `python3 .assign_collections.py` to regenerate both .js files.
3. In Zotero: Tools → Developer → Run JavaScript (make sure `async` is ON).
4. Paste `.cleanup_collections.js`, click Run. Wait for summary.
5. Paste `.assign_collections.js`, click Run.
"""

import json
import re
import sys
from pathlib import Path

# Paths resolve relative to this script (files/zotero-sync/), so it runs from any CWD.
SCRIPT_DIR = Path(__file__).resolve().parent
BIB_FILE = str(SCRIPT_DIR / "orphan.bib")
OUT_ASSIGN = str(SCRIPT_DIR / ".assign_collections.js")
OUT_CLEANUP = str(SCRIPT_DIR / ".cleanup_collections.js")


def parse_orphan_bib(path):
    """Yield {citationKey, title, paths} dicts. Paths are pre-split into [seg,seg,...]."""
    content = Path(path).read_text(encoding="utf-8")
    entries = []
    for m in re.finditer(r"@\w+\{([^,]+),(.*?)\n\}\n", content, re.DOTALL):
        citation_key = m.group(1).strip()
        body = m.group(2)
        title_m = re.search(r"title\s*=\s*\{([^}]+)\}", body)
        groups_m = re.search(r"groups\s*=\s*\{([^}]+)\}", body)
        if not title_m:
            continue
        title = title_m.group(1).strip()
        paths = []
        if groups_m:
            for raw in groups_m.group(1).split(","):
                raw = raw.strip()
                if not raw:
                    continue
                paths.append([seg.strip() for seg in raw.split("/") if seg.strip()])
        entries.append(
            {"citationKey": citation_key, "title": title, "paths": paths}
        )
    return entries


ASSIGN_TEMPLATE = r"""// Auto-generated by .assign_collections.py
// Paste into Zotero: Tools → Developer → Run JavaScript (async ON), then click Run.
//
// What it does:
//   1. Looks up each item by citationKey via BBT KeyManager (filters out trashed)
//   2. For each path (e.g. ["🗺️ games", "⇶ world of warcraft", "⚡ holy priest"])
//      ensures collections exist with proper parent-child nesting
//   3. Adds the item to the LEAF collection only
// Idempotent: re-running is safe.

const ASSIGNMENTS = __ASSIGNMENTS_JSON__;

const libraryID = Zotero.Libraries.userLibraryID;
const log = (s) => Zotero.debug("[assign] " + s);

// Cache: "parentID|name" -> collection ID
const cache = new Map();
function cacheKey(parentID, name) { return (parentID == null ? "0" : parentID) + "|" + name; }

// Pre-fill cache with existing collections (incl. subcollections)
const existingColls = Zotero.Collections.getByLibrary(libraryID, true);
for (const c of existingColls) {
    cache.set(cacheKey(c.parentID || null, c.name), c.id);
}
log("Existing collections in library: " + existingColls.length);

async function ensureCollection(parentID, name) {
    const k = cacheKey(parentID, name);
    if (cache.has(k)) return cache.get(k);
    const coll = new Zotero.Collection();
    coll.libraryID = libraryID;
    coll.name = name;
    if (parentID != null) coll.parentID = parentID;
    const id = await coll.saveTx();
    cache.set(k, id);
    log("Created collection: " + name + " (parent=" + (parentID || "root") + ", id=" + id + ")");
    return id;
}

async function ensurePath(segments) {
    let parentID = null;
    for (const seg of segments) {
        parentID = await ensureCollection(parentID, seg);
    }
    return parentID;
}

// Title fallback lookup (case-insensitive)
const allItems = await Zotero.Items.getAll(libraryID, true, false, false);
const titleToItem = new Map();
for (const it of allItems) {
    if (it.deleted) continue;
    if (it.itemType === "attachment" || it.itemType === "note") continue;
    const t = (it.getField("title") || "").trim().toLowerCase();
    if (t && !titleToItem.has(t)) titleToItem.set(t, it);
}
log("Live non-attachment items: " + titleToItem.size);

let updatedCount = 0;
let notFoundCount = 0;
let titleFallbackCount = 0;
const notFoundList = [];

for (const a of ASSIGNMENTS) {
    let item = null;

    // 1. Try KeyManager — filter out trashed
    try {
        const found = Zotero.BetterBibTeX.KeyManager.find({
            citationKey: a.citationKey,
            libraryID: libraryID,
        });
        if (found && found.length > 0) {
            for (const f of found) {
                const candidate = await Zotero.Items.getAsync(f.itemID);
                if (candidate && !candidate.deleted) {
                    item = candidate;
                    break;
                }
            }
        }
    } catch (e) {
        log("KeyManager error for " + a.citationKey + ": " + e.message);
    }

    // 2. Fallback: case-insensitive title
    if (!item) {
        const found = titleToItem.get(a.title.toLowerCase());
        if (found) {
            item = found;
            titleFallbackCount++;
        }
    }

    if (!item) {
        notFoundCount++;
        notFoundList.push(a.citationKey + " / " + a.title);
        continue;
    }

    // Build leaf IDs for all paths
    const leafIDs = [];
    for (const segments of a.paths) {
        if (segments.length === 0) continue;
        const leaf = await ensurePath(segments);
        leafIDs.push(leaf);
    }

    const current = item.getCollections();
    const toAdd = leafIDs.filter(id => !current.includes(id));
    if (toAdd.length === 0) continue;

    item.setCollections([...current, ...toAdd]);
    await item.saveTx();
    updatedCount++;
}

const summary =
    "Updated " + updatedCount + " items " +
    "(" + titleFallbackCount + " via title fallback); " +
    notFoundCount + " not found. Cache had " +
    cache.size + " collection entries at the end.";
log(summary);
if (notFoundList.length > 0) {
    log("Sample not found: " + notFoundList.slice(0, 10).join("; "));
}
return summary;
"""


CLEANUP_TEMPLATE = r"""// Auto-generated cleanup script
// Paste into Zotero: Tools → Developer → Run JavaScript (async ON), then Run.
//
// Removes every item from collections whose name starts with 🗺️, ⇶, or ⚡.
// Items themselves are NOT deleted — just their membership in those collections.
// Use this to undo a bad assignment run before re-assigning.

const libraryID = Zotero.Libraries.userLibraryID;
const log = (s) => Zotero.debug("[cleanup] " + s);

const allColls = Zotero.Collections.getByLibrary(libraryID, true);
const emojiCollIDs = new Set();
const emojiCollNames = [];
const emojiRe = /^(🗺️|⇶|⚡)/u;
for (const c of allColls) {
    if (emojiRe.test(c.name)) {
        emojiCollIDs.add(c.id);
        emojiCollNames.push(c.name);
    }
}
log("Emoji-prefixed collections found: " + emojiCollIDs.size);

const allItems = await Zotero.Items.getAll(libraryID, true, false, false);
let touched = 0;
for (const item of allItems) {
    if (item.deleted) continue;
    const colls = item.getCollections();
    if (colls.length === 0) continue;
    const filtered = colls.filter(cid => !emojiCollIDs.has(cid));
    if (filtered.length === colls.length) continue;
    item.setCollections(filtered);
    await item.saveTx();
    touched++;
}

const summary =
    "Cleared " + touched + " items from " + emojiCollIDs.size +
    " emoji-prefixed collections. Empty collections remain — delete manually if desired.";
log(summary);
return summary;
"""


def main():
    bib_path = Path(BIB_FILE)
    if not bib_path.exists():
        sys.exit(f"❌ {BIB_FILE} not found. Run .generate_bibtex.py first.")

    entries = parse_orphan_bib(BIB_FILE)
    if not entries:
        sys.exit(f"❌ No entries parsed from {BIB_FILE}.")

    payload = [
        {"citationKey": e["citationKey"], "title": e["title"], "paths": e["paths"]}
        for e in entries
        if e["paths"]
    ]
    payload_json = json.dumps(payload, ensure_ascii=False, indent=2)

    Path(OUT_ASSIGN).write_text(
        ASSIGN_TEMPLATE.replace("__ASSIGNMENTS_JSON__", payload_json),
        encoding="utf-8",
    )
    Path(OUT_CLEANUP).write_text(CLEANUP_TEMPLATE, encoding="utf-8")

    unique_segs = sorted({seg for e in payload for p in e["paths"] for seg in p})
    n_paths = sum(len(e["paths"]) for e in payload)

    print(f"📚 Parsed {len(entries)} entries ({len(payload)} with paths, {n_paths} paths total)")
    print(f"🗂  {len(unique_segs)} unique path segments (collections to ensure)")
    print(f"✅ Wrote {OUT_ASSIGN} ({Path(OUT_ASSIGN).stat().st_size} bytes)")
    print(f"✅ Wrote {OUT_CLEANUP} ({Path(OUT_CLEANUP).stat().st_size} bytes)")
    print()
    print("Workflow:")
    print("  1. In Zotero, right-click Trash → Empty Trash (clears stale BBT records)")
    print(f"  2. Tools → Developer → Run JavaScript → paste {OUT_CLEANUP} → Run")
    print(f"  3. Tools → Developer → Run JavaScript → paste {OUT_ASSIGN} → Run")


if __name__ == "__main__":
    main()
