#!/usr/bin/env python3
"""Generate a collection-assignment JS that matches items by explicit Zotero
itemKey — NOT by BBT citation key.

Why: Zotero.BetterBibTeX.KeyManager.find({citationKey}) is broken in this library
and returns the SAME item (itemID=1, "ВНУТРЯНКА АЙТИ") for every query, so the
old .assign_collections.js placed one item into all 18 leaf collections. Matching
by stable itemKey sidesteps KeyManager entirely.

Resolution (done HERE, against the live read-only Zotero API while Zotero runs):
  orphan.bib title  →  the single item with that title INSIDE the `orphan`
  import collection. Verified 1:1 for all 98 (0 ambiguous, 0 miss).

Output: `.assign_collections.js` (overwrites). Run order in Zotero:
  1. `.cleanup_collections.js`  (clears the bad ВНУТРЯНКА АЙТИ placements)
  2. `.assign_collections.js`   (this — places all 98 correctly by itemKey)
"""

import json
import re
import sys
import urllib.request
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
BIB_FILE = str(SCRIPT_DIR / "orphan.bib")
OUT_ASSIGN = str(SCRIPT_DIR / ".assign_collections.js")
API = "http://127.0.0.1:23119/api/users/0"


def api_get(path):
    with urllib.request.urlopen(API + path, timeout=15) as r:
        return json.load(r)


def orphan_title_to_key():
    colls = api_get("/collections?limit=200")
    match = [c["data"]["key"] for c in colls if c["data"]["name"] == "orphan"]
    if not match:
        sys.exit("❌ No `orphan` collection found via Zotero API.")
    ok = match[0]
    title_to_key, start = {}, 0
    while True:
        batch = api_get(f"/collections/{ok}/items?limit=100&start={start}&format=json")
        if not batch:
            break
        for it in batch:
            d = it["data"]
            if d.get("itemType") in ("attachment", "note"):
                continue
            t = (d.get("title") or "").strip().lower()
            if t:
                title_to_key.setdefault(t, []).append(it["key"])
        start += 100
        if len(batch) < 100:
            break
    return title_to_key


def parse_bib(path):
    content = Path(path).read_text(encoding="utf-8")
    out = []
    for m in re.finditer(r"@\w+\{([^,]+),(.*?)\n\}\n", content, re.DOTALL):
        body = m.group(2)
        tm = re.search(r"title\s*=\s*\{([^}]+)\}", body)
        gm = re.search(r"groups\s*=\s*\{([^}]+)\}", body)
        if not tm:
            continue
        paths = []
        if gm:
            for raw in gm.group(1).split(","):
                raw = raw.strip()
                if raw:
                    paths.append([s.strip() for s in raw.split("/") if s.strip()])
        out.append({"title": tm.group(1).strip(), "paths": paths})
    return out


JS_TEMPLATE = r"""// Auto-generated by .assign_by_itemkey.py — matches by stable itemKey (NOT citationKey).
// Zotero → Tools → Developer → Run JavaScript (async ON) → Run.
// Run .cleanup_collections.js FIRST to clear the earlier bad placements.

const ASSIGNMENTS = __ASSIGNMENTS_JSON__;
const libraryID = Zotero.Libraries.userLibraryID;
const log = (s) => Zotero.debug("[assign-v2] " + s);

const cache = new Map();
const ck = (p, n) => (p == null ? "0" : p) + "|" + n;
for (const c of Zotero.Collections.getByLibrary(libraryID, true)) {
    cache.set(ck(c.parentID || null, c.name), c.id);
}

async function ensureCollection(parentID, name) {
    const k = ck(parentID, name);
    if (cache.has(k)) return cache.get(k);
    const coll = new Zotero.Collection();
    coll.libraryID = libraryID;
    coll.name = name;
    if (parentID != null) coll.parentID = parentID;
    const id = await coll.saveTx();
    cache.set(k, id);
    return id;
}
async function ensurePath(segs) {
    let p = null;
    for (const s of segs) p = await ensureCollection(p, s);
    return p;
}

let updated = 0, already = 0, notFound = 0;
const notFoundList = [];

for (const a of ASSIGNMENTS) {
    const item = await Zotero.Items.getByLibraryAndKeyAsync(libraryID, a.itemKey);
    if (!item || item.deleted) { notFound++; notFoundList.push(a.itemKey); continue; }

    const leafIDs = [];
    for (const segs of a.paths) {
        if (!segs.length) continue;
        leafIDs.push(await ensurePath(segs));
    }
    const current = item.getCollections();
    const toAdd = leafIDs.filter(id => !current.includes(id));
    if (!toAdd.length) { already++; continue; }

    item.setCollections([...current, ...toAdd]);
    await item.saveTx();
    updated++;
}

const summary = "Placed " + updated + " items; " + already +
    " already correct; " + notFound + " not found.";
log(summary);
if (notFoundList.length) log("Not found keys: " + notFoundList.slice(0, 10).join(", "));
return summary;
"""


def main():
    title_to_key = orphan_title_to_key()
    entries = parse_bib(BIB_FILE)

    payload, miss, amb = [], [], []
    for e in entries:
        if not e["paths"]:
            continue
        keys = title_to_key.get(e["title"].strip().lower(), [])
        if len(keys) == 1:
            payload.append({"itemKey": keys[0], "paths": e["paths"]})
        elif len(keys) > 1:
            amb.append(e["title"])
        else:
            miss.append(e["title"])

    Path(OUT_ASSIGN).write_text(
        JS_TEMPLATE.replace(
            "__ASSIGNMENTS_JSON__", json.dumps(payload, ensure_ascii=False, indent=2)
        ),
        encoding="utf-8",
    )
    print(f"✅ Resolved {len(payload)} items by itemKey → {OUT_ASSIGN}")
    if amb:
        print(f"⚠️  {len(amb)} ambiguous (skipped): {amb}")
    if miss:
        print(f"⚠️  {len(miss)} unresolved (skipped): {miss}")
    print("\nIn Zotero (async ON): run .cleanup_collections.js, then .assign_collections.js")


if __name__ == "__main__":
    main()
