#!/usr/bin/env python3
"""Resolve a `creator` for orphan.bib entries that imported as author={Unknown}.

Only entries WITH a URL get a creator — there's no honest author signal for
URL-less notes, so they stay Unknown. Heuristics, best→weakest:

- youtube.com / youtu.be  → channel name via public oEmbed (no API key)
- github.com/<owner>/...   → repo owner
- t.me/<channel>           → Telegram channel handle (@ stripped)
- anything else            → registrable domain as a publisher-ish creator

Output: `.enrich_authors.js` — paste into Zotero (Tools → Developer → Run
JavaScript, async ON). Matches each item by citationKey via BBT KeyManager and
sets a single-field (institutional) creator. Idempotent: only sets a creator on
items whose sole creator is missing/"Unknown", so it won't clobber real authors.
"""

import json
import re
import sys
import urllib.parse
import urllib.request
from pathlib import Path
from urllib.parse import urlparse

# Paths resolve relative to this script (files/zotero-sync/), so it runs from any CWD.
SCRIPT_DIR = Path(__file__).resolve().parent
BIB_FILE = str(SCRIPT_DIR / "orphan.bib")
OUT_JS = str(SCRIPT_DIR / ".enrich_authors.js")


def parse_unknown_with_url(path):
    content = Path(path).read_text(encoding="utf-8")
    out = []
    for m in re.finditer(r"@\w+\{([^,]+),(.*?)\n\}\n", content, re.DOTALL):
        key, body = m.group(1).strip(), m.group(2)
        author = (re.search(r"author\s*=\s*\{([^}]*)\}", body) or [None, ""])
        author = re.search(r"author\s*=\s*\{([^}]*)\}", body)
        author = author.group(1).strip() if author else ""
        if author != "Unknown":
            continue
        url = re.search(r"url\s*=\s*\{([^}]*)\}", body)
        url = url.group(1).strip() if url else ""
        if not url:
            continue
        title = re.search(r"title\s*=\s*\{([^}]*)\}", body)
        title = title.group(1).strip() if title else ""
        out.append({"key": key, "url": url, "title": title})
    return out


def youtube_channel(url):
    api = "https://www.youtube.com/oembed?" + urllib.parse.urlencode(
        {"url": url, "format": "json"}
    )
    try:
        with urllib.request.urlopen(api, timeout=12) as r:
            return json.load(r).get("author_name") or None
    except Exception as e:
        print(f"   ! oEmbed failed for {url}: {e}", file=sys.stderr)
        return None


def resolve_creator(url):
    host = urlparse(url).netloc.replace("www.", "")
    path = urlparse(url).path.strip("/")
    if host in ("youtube.com", "youtu.be", "m.youtube.com"):
        ch = youtube_channel(url)
        return (ch, "youtube") if ch else (None, "youtube-failed")
    if host == "github.com":
        owner = path.split("/")[0] if path else ""
        return (owner or None, "github")
    if host == "t.me":
        seg = path.split("/")[0] if path else ""
        ch = seg.lstrip("@")
        # t.me/c/<id>/... is a private-channel numeric link — no usable handle
        if ch in ("c", "s", "joinchat", "+") or ch.isdigit():
            return (None, "telegram-private")
        return (ch or None, "telegram")
    # weak fallback: domain as publisher
    return (host or None, "domain") if host else (None, "none")


JS_TEMPLATE = r"""// Auto-generated by .enrich_authors.py
// Zotero → Tools → Developer → Run JavaScript (async ON) → Run.
// Sets a single-field creator on imported items that have no real author yet.
// Idempotent + safe: skips any item that already has a non-"Unknown" creator.

const CREATORS = __CREATORS_JSON__;  // {itemKey, creator}
const libraryID = Zotero.Libraries.userLibraryID;
const log = (s) => Zotero.debug("[authors] " + s);

let set = 0, skipped = 0, notFound = 0;
const notFoundList = [];

for (const c of CREATORS) {
    // Match by stable itemKey — NOT BBT KeyManager (which is broken in this library).
    const item = await Zotero.Items.getByLibraryAndKeyAsync(libraryID, c.itemKey);
    if (!item || item.deleted) { notFound++; notFoundList.push(c.itemKey); continue; }

    const existing = item.getCreators();
    const hasReal = existing.some(cr => {
        const n = (cr.name || ((cr.lastName||"") + " " + (cr.firstName||""))).trim();
        return n && n.toLowerCase() !== "unknown";
    });
    if (hasReal) { skipped++; continue; }

    item.setCreators([{ creatorTypeID: Zotero.CreatorTypes.getPrimaryIDForType(item.itemTypeID),
                        name: c.creator, fieldMode: 1 }]);
    await item.saveTx();
    set++;
}

const summary = "Set creator on " + set + " items; skipped " + skipped +
    " (already had author); " + notFound + " not found.";
log(summary);
if (notFoundList.length) log("Not found: " + notFoundList.slice(0,10).join(", "));
return summary;
"""


API = "http://127.0.0.1:23119/api/users/0"


def orphan_title_to_key():
    """title → itemKey, resolved within the `orphan` import collection (1:1)."""
    def api_get(path):
        with urllib.request.urlopen(API + path, timeout=15) as r:
            return json.load(r)
    colls = api_get("/collections?limit=200")
    match = [c["data"]["key"] for c in colls if c["data"]["name"] == "orphan"]
    if not match:
        sys.exit("❌ No `orphan` collection found via Zotero API (is Zotero running?).")
    ok, start, t2k = match[0], 0, {}
    while True:
        batch = api_get(f"/collections/{ok}/items?limit=100&start={start}&format=json")
        if not batch:
            break
        for it in batch:
            d = it["data"]
            if d.get("itemType") in ("attachment", "note"):
                continue
            t = (d.get("title") or "").strip().lower()
            if t:
                t2k.setdefault(t, []).append(it["key"])
        start += 100
        if len(batch) < 100:
            break
    return t2k


def main():
    if not Path(BIB_FILE).exists():
        sys.exit(f"❌ {BIB_FILE} not found.")
    items = parse_unknown_with_url(BIB_FILE)
    print(f"📚 {len(items)} Unknown-author entries have a URL")

    title_to_key = orphan_title_to_key()

    resolved, by_method, unresolved_key = [], {}, 0
    for it in items:
        creator, method = resolve_creator(it["url"])
        by_method[method] = by_method.get(method, 0) + 1
        if not creator:
            print(f"   · [{method:8}] {it['title'][:40]:40} → (no creator)")
            continue
        keys = title_to_key.get(it["title"].strip().lower(), [])
        if len(keys) != 1:
            unresolved_key += 1
            print(f"   ✗ [{method:8}] {it['title'][:40]:40} → {creator} (itemKey x{len(keys)})")
            continue
        resolved.append({"itemKey": keys[0], "creator": creator})
        print(f"   ✓ [{method:8}] {it['title'][:40]:40} → {creator}")

    payload = json.dumps(resolved, ensure_ascii=False, indent=2)
    Path(OUT_JS).write_text(
        JS_TEMPLATE.replace("__CREATORS_JSON__", payload), encoding="utf-8"
    )
    print(f"\n🔧 by method: {by_method}")
    print(f"✅ Wrote {OUT_JS}: {len(resolved)} creator assignments")
    print(f"   {len(items) - len(resolved)} URL items unresolved; "
          f"URL-less Unknowns left as-is by design.")


if __name__ == "__main__":
    main()
