#!/usr/bin/env python3
"""Generate `.orphan_missing.bib` for source notes that were wrongly skipped by
.generate_bibtex.py (its crude `"zotero:" in content` check matched an empty
`zotero:` frontmatter key or `zotero://` links in the note body), so they never
got a Zotero item.

Same conventions as .generate_bibtex.py (citation key, keywords, nested groups).
Import the result into Zotero (File → Import), then re-run .assign_all_sources.py.
"""

import re
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
VAULT_ROOT = SCRIPT_DIR.parents[1]
SOURCES = VAULT_ROOT / "sources"
OUT = SCRIPT_DIR / ".orphan_missing.bib"

# Notes confirmed absent from Zotero (have a category but no resolvable item).
TARGETS = [
    "народный пк от welson",
    "Вопросы и ответы к интервью Java разработчика",
]

TYPE_MAP = {
    "source/article/paper": "article",
    "source/book": "book",
    "source/video/recording": "misc",
    "source/article/resource": "misc",
    "source/course": "misc",
}


def sanitize_key(name):
    name = name.replace(" ", "_").replace("-", "_")
    name = re.sub(r"[^a-zA-Z0-9_Ѐ-ӿ]", "", name)
    name = re.sub(r"_+", "_", name).strip("_").lower()
    return (name or "untitled")[:80]


def clean_url(u):
    u = u.strip()
    m = re.search(r"\((https?://[^)]+)\)", u)  # markdown link form
    if m:
        u = m.group(1)
    return u.rstrip(").,")


def fm_of(content):
    return content.split("---", 2)[1] if content.startswith("---") else ""


def main():
    entries = []
    for stem in TARGETS:
        f = SOURCES / f"{stem}.md"
        if not f.exists():
            print(f"⚠️ missing file: {f}")
            continue
        c = f.read_text(encoding="utf-8")
        fm = fm_of(c)

        am = re.search(r'aliases:\s*\n\s*-\s*"?(.+?)"?\s*$', fm, re.M)
        alias = am.group(1).strip() if am and am.group(1).strip() not in ("[]", "") else ""
        title = alias or stem
        key = sanitize_key(stem)

        types = re.findall(r"source/([\w/]+)", fm)
        ztype = ("source/" + types[0]) if types else ""
        bibtype = TYPE_MAP.get(ztype, "misc")

        cats = re.findall(r'category:\s*\n\s*-\s*"\[\[(.+?)\]\]"', fm)
        metas = re.findall(r'meta:\s*\n\s*-\s*"\[\[(.+?)\]\]"', fm)
        probs = re.findall(r'problem:\s*\n\s*-\s*"\[\[(.+?)\]\]"', fm)
        status = re.search(r"status:\s*(📥|🟥|🟦|🟩|❄|⬛|⚛)", fm)
        status = status.group(1) if status else None

        um = re.search(r'url:\s*\n\s*-\s*(.+)', fm) or re.search(r'url:\s*"?(.+?)"?\s*$', fm, re.M)
        url = clean_url(um.group(1)) if um else ""

        # nested groups (same as generate_bibtex)
        groups, metas_list, probs_list = [], metas or [None], probs or [None]
        for cat in cats:
            base = f"🗺️ {cat}"
            for meta in metas_list:
                mid = base + (f"/⇶ {meta}" if meta else "")
                for prob in probs_list:
                    full = mid + (f"/⚡ {prob}" if prob else "")
                    if full not in groups:
                        groups.append(full)

        lines = [f"% Original: sources/{f.name}", f"@{bibtype}{{{key},",
                 f"  title = {{{title}}},", "  author = {Unknown},"]
        if status:
            lines.append(f"  keywords = {{{status}}},")
        if groups:
            lines.append(f"  groups = {{{', '.join(groups)}}},")
        if url.startswith("http"):
            lines.append(f"  url = {{{url}}},")
        lines.append(f"  note = {{Obsidian source: {stem}}}")
        lines.append("}")
        entries.append("\n".join(lines))
        print(f"  ✓ {key}  | type={bibtype} | cats={cats} | groups={groups} | url={url or '-'}")

    OUT.write_text(
        "% Generated by .gen_missing_bib.py — import via File → Import\n\n"
        + "\n\n".join(entries) + "\n",
        encoding="utf-8",
    )
    print(f"\n✅ Wrote {OUT} ({len(entries)} entries)")


if __name__ == "__main__":
    main()
