#!/usr/bin/env python3
"""One-way push of knowledge-state from Obsidian → Zotero (Obsidian always wins).

Mirrors each source note's status / rating / scientificity into Zotero as tags,
so you can filter by them in Zotero too. Obsidian is the single source of truth:
this only ever WRITES to Zotero, never reads state back.

Workflow:
  1. python3 files/zotero-sync/.push_status.py   # reads notes → writes .push_status.js
  2. In Zotero: Tools → Developer → Run JavaScript (async ON) → paste → Run

The generated JS, per item: removes any existing tag from the status/rating/
scientificity vocabularies, then adds the note's current values. Idempotent, and
transitions propagate (e.g. 🟥→🟩 removes 🟥). Matches by stable itemKey.

Category/meta/problem changes are NOT handled here — re-run .assign_all_sources.py
for those (collection membership).
"""

import json
import re
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
VAULT_ROOT = SCRIPT_DIR.parents[1]
SOURCES_DIR = VAULT_ROOT / "sources"
LIBRARY_FILE = SCRIPT_DIR / ".library.json"
OUT_JS = SCRIPT_DIR / ".push_status.js"

STATUS_VOCAB = ["📥", "🟥", "🟦", "🟩", "❄", "⬛", "⚛"]
RATING_VOCAB = ["🌕", "🌔", "🌓", "🌒", "🌑"]
SCIENT_VOCAB = ["🅰️", "🅱️", "👓", "📢", "💬"]


def citationkey_to_itemkey():
    lib = json.loads(LIBRARY_FILE.read_text(encoding="utf-8"))
    out = {}
    for it in lib["items"]:
        ck, uri = it.get("citationKey"), it.get("uri", "")
        if ck and uri:
            out[ck] = uri.rsplit("/", 1)[-1]
    return out


def fm_field(fm, key, vocab):
    m = re.search(rf"^{key}:\s*(\S+)", fm, re.M)
    if not m:
        return None
    val = m.group(1).strip().strip('"')
    return val if val in vocab else None


def main():
    ck2ik = citationkey_to_itemkey()
    payload, no_item = [], []
    for f in sorted(SOURCES_DIR.glob("*.md")):
        c = f.read_text(encoding="utf-8")
        fm = c.split("---", 2)[1] if c.startswith("---") else ""
        m = re.search(r"zotero://select(?:/library)?/items/@([\w\-]+)", c)
        if not m:
            continue
        ik = ck2ik.get(m.group(1))
        if not ik:
            no_item.append(f.stem)
            continue
        payload.append({
            "itemKey": ik,
            "status": fm_field(fm, "status", STATUS_VOCAB),
            "rating": fm_field(fm, "rating", RATING_VOCAB),
            "scientificity": fm_field(fm, "scientificity", SCIENT_VOCAB),
        })

    js = JS_TEMPLATE
    for name, vocab in [("STATUS_VOCAB", STATUS_VOCAB), ("RATING_VOCAB", RATING_VOCAB),
                        ("SCIENT_VOCAB", SCIENT_VOCAB)]:
        js = js.replace("__%s__" % name, json.dumps(vocab, ensure_ascii=False))
    js = js.replace("__PAYLOAD__", json.dumps(payload, ensure_ascii=False, indent=2))
    OUT_JS.write_text(js, encoding="utf-8")

    n_status = sum(1 for p in payload if p["status"])
    print(f"✅ {len(payload)} items → {OUT_JS}")
    print(f"   with status: {n_status} | rating: {sum(1 for p in payload if p['rating'])}"
          f" | scientificity: {sum(1 for p in payload if p['scientificity'])}")
    if no_item:
        print(f"⚠️ {len(no_item)} notes with a link but no item in library: {no_item[:5]}")
    print("\nPaste .push_status.js into Zotero (Tools → Developer → Run JavaScript, async ON).")


JS_TEMPLATE = r"""// Auto-generated by .push_status.py — ONE-WAY Obsidian → Zotero (Obsidian wins).
// Zotero → Tools → Developer → Run JavaScript (async ON) → Run.

const STATUS_VOCAB = __STATUS_VOCAB__;
const RATING_VOCAB = __RATING_VOCAB__;
const SCIENT_VOCAB = __SCIENT_VOCAB__;
const ITEMS = __PAYLOAD__;
const ALL = new Set([...STATUS_VOCAB, ...RATING_VOCAB, ...SCIENT_VOCAB]);

const libraryID = Zotero.Libraries.userLibraryID;
const log = (s) => Zotero.debug("[push-status] " + s);

let changed = 0, notFound = 0;
const notFoundList = [];

for (const it of ITEMS) {
    const item = await Zotero.Items.getByLibraryAndKeyAsync(libraryID, it.itemKey);
    if (!item || item.deleted) { notFound++; notFoundList.push(it.itemKey); continue; }

    const want = [it.status, it.rating, it.scientificity].filter(Boolean);
    const current = item.getTags().map(t => t.tag);
    let dirty = false;

    // remove any managed-vocabulary tag that isn't the desired value
    for (const tag of current) {
        if (ALL.has(tag) && !want.includes(tag)) { item.removeTag(tag); dirty = true; }
    }
    // add desired values that are missing
    for (const tag of want) {
        if (!item.hasTag(tag)) { item.addTag(tag); dirty = true; }
    }
    if (dirty) { await item.saveTx(); changed++; }
}

const summary = "Pushed state to Zotero: " + changed + " items changed; " + notFound + " not found.";
log(summary);
if (notFoundList.length) log("Not found: " + notFoundList.slice(0, 10).join(", "));
return summary;
"""


if __name__ == "__main__":
    main()
